### ISSUE TITLE
Wish List:  run a percentage of the total design space

### ISSUE THREAD

**Issue by TheodoreGalanos** [tt-acm/Colibri.Grasshopper#11]
Firstly I'd like to say thanks for this cool project! I feel it's going to be very helpful and is coming at the right time considering how parametric models are becoming more and more popular.

I will try and add a few wishes mainly based on my latest on-going project, connecting Machine Learning and parametric modelling, through HB/LB/GH/DesignExplorer. In order to make things easier for responding to these I will split them up in separate issues. I hope that is ok, let me know if you want an aggregated post.

The first one, which is quite related to #10 is to add an option for Colibri to run a percentage of the design space, set by the user. 

While selecting a number of iterations to run as a means of testing the sanity of the definition is fine (see #10), a percentage of simulations is something you would want to select in production models and stages. It is also critical for ML applications, where you only select a part of your design space to run.

Furthermore, there are two things that this has to achieve:

- random selection of design instances from the whole design space
- stratified selection across model parameters (i.e. as much as possible select equal instances of different parameters), in order to reduce the bias in the training set.

That's all for this one! Thanks!

Kind regards,
Theodore

**Comment by MingboPeng** [comment]
@TheodoreGalanos actually, this is one of my wish list as well. I am thinking add another option on your "selection" modes:  range selection to run a certain range of whole, so that we can split the simulation work to different computer.  Thanks for you suggestion.

**Comment by MingboPeng** [comment]
@TheodoreGalanos setting up the steps for each slider can actually do stratified selection as you described. @bhowes-tt

**Comment by TheodoreGalanos** [comment]
@MingboPeng I have to admit I haven't tried a Colibri definition yet, so I haven't used the steps slider if it is implemented. Would this step slider force some parameter values to be altogether skipped? If yes, the output design space might be stratified but it would also miss some parameter combinations all together. Or does it mean it scrolls through the list of all possible combinations, keeping every n_step row?

Kind regards,
Theodore.
