### ISSUE TITLE
Wish List: option to export the whole design space to csv file

### ISSUE THREAD

**Issue by TheodoreGalanos** [tt-acm/Colibri.Grasshopper#12]
Hello,

It would be really helpful for ML applications to add the option of exporting the whole design space (i.e. the csv file of all the different combinations of input model parameters, without the results) to a .csv file.

So far in my parametric models I have been achieving this using the fly component along with native GH components to save and export to excel. It'd be neat to have this within one component.

Kind regards,
Theodore.

**Comment by MingboPeng** [comment]
@TheodoreGalanos , thanks, and very good suggestion. will be added in next version.

**Comment by TheodoreGalanos** [comment]
@MingboPeng Excellent! :+1:
