### ISSUE TITLE
Wish List: export and import both standard and DesignExplorer csv formats

### ISSUE THREAD

**Issue by TheodoreGalanos** [tt-acm/Colibri.Grasshopper#13]
Hello,

The current work flow I am using incorporating supervised learning to parametric models consists of exporting an initial csv input file of the whole design space (see #12), exporting a .csv result file of a percentage of the design space (see #11), applying supervised learning that generates the .csv result file for the whole design space. 

Given the special format of DesignExplorer it would be nice if there was an option to automatically change an input .csv to (and fro) a DesignExplorer format. Ofc this is all too easy manually but why not automate it!

Kind regards,
Theodore.

**Comment by MingboPeng** [comment]
@TheodoreGalanos  thanks, I like this idea a lot. I was thinking to add this feature to DesignExplorer, for those who doesn't use grasshopper, can actually do all converting work in DesignExplorer. 
@mostaphaRoudsari
