### ISSUE TITLE
Wish List: Skip already completed instances of the design space

### ISSUE THREAD

**Issue by TheodoreGalanos** [tt-acm/Colibri.Grasshopper#15]
Hello, 

First of all congratulations on the release, I've been testing Colibri and it's quite nice!

As you might have witnessed, during parametric runs a lot of things can happen that might disrupt the simulation. In that case we are left with a .csv file that is incomplete.

Is it possible to restart the run, while Colibri reads the already existing data.csv and skips the runs previously completed?

Thanks in advance!

Kind regards,
Theodore.

**Comment by MingboPeng** [comment]
Hi @TheodoreGalanos ,

Thanks for your suggestion.
We just finished a new version of Colibri this week. The problem that you stated can be easily fixed in new version.
You can set run ranges manually instead of rerun all.
We are doing some final tests before release. (most of your previous suggestions have been included)

I will let you know once it becomes stable.

Thanks,
Mingbo

**Comment by TheodoreGalanos** [comment]
@MingboPeng That sounds amazing! Can't wait to test it out.

As for my issue above I think it is not that serious as long as the freeze happens near the beginning of the run. In my case I just re-run the whole thing and I can remove duplicate lines later. But ofc if this is towards the middle, then you don't want to re-do it half of it again.

Again great work!

Kind regards,
Theodore.

**Comment by TheodoreGalanos** [comment]
@MingboPeng I take it back! Forgot to turn off Windows update on my new pc and the computer obviously restarted after 2 1/2 days of running daylight simulations :)

I have a suggestion for an easy way to handle this. You could have an additional input in the aggregator component. This input would take a list of already completed combinations of sliders (easy to import those from the data.csv that has already been created). These combinations would then be 'culled' from the design space of the attached sliders. 

This is quite easy to do in pandas so I imagine it can be done with native python as well.

Anyways just an idea!

Kind regards,
Theodore.

**Comment by MingboPeng** [comment]
@TheodoreGalanos  added, and releasing soon:>

**Comment by TheodoreGalanos** [comment]
@MingboPeng Excellent thanks!
