### ISSUE TITLE
BUG: Input Names do not Correspond to the Input Data

### ISSUE THREAD

**Issue by chriswmackey** [tt-acm/Colibri.Grasshopper#16]
I have discovered a fairly large bug in Colibri that is currently making it difficult to use.  Namely, the names of Inputs from the Iterator do not match the actual data:
![image](https://cloud.githubusercontent.com/assets/5567574/24213512/134fae66-0f09-11e7-9cd8-1fd4a2fbafd7.png)

It seems to be a fairly simple bug to fix (just a list management issue) and it would stop me from having to manually edit the output CSV file after running Colibri.  Here's a GH file that shows the issue:
https://www.dropbox.com/s/os3u9yagzstd5m9/colibriBug.gh?dl=0

-Chris

**Comment by MingboPeng** [comment]
Hi @chriswmackey , thanks for testing it. I have noticed this problem, and has been fixed in a brand new version that I worked on it for several weeks. We are still testing it before the release. 
Please let me know if you need, and I can send you email with new version.
Mingbo

**Comment by chriswmackey** [comment]
Thanks, @MingboPeng .  I'm looking forward to seeing it in the next release of TTToolbox.

**Comment by chriswmackey** [comment]
@MingboPeng ,
Thanks again for your support of this.  You might already aware of this but I found an issue with the new Colibri that you sent.  Specifically, it was failing to write some results into the data.csv file every once in a while.  It's a hard issue to replicate as the component is clearly able to write some results into the data.csv file correctly and I could not figure what was causing some lines to not be written correctly (see lines highlighted in red below).
![image](https://cloud.githubusercontent.com/assets/5567574/26004431/d9948fc0-3703-11e7-85a9-3cb91facea3b.png)

I have also witnessed this with the current Colibri but it's much rarer than with the new Colibri.  Let me know if you would like me to open another issue and upload a file that tries to recreate it.  I'll warn that such a file will likely take some time to run. though.
-Chris

**Comment by MingboPeng** [comment]
@chriswmackey  Thanks for your test. Yes, I have noticed this problem, and fixed the issue I found. However, from what you highlighted in CSV file, it seems those lines don't have data from column "J" to "M", may I ask what those data are, and is there any possible that those data are "null" from upstream components?
Did you tried the [newest build version](https://github.com/MingboPeng/Colibri.Grasshopper/blob/master/src/Colibri.Grasshopper/bin/Colibri.Grasshopper.gha)? 
Please upload a test file that has the same problem if this still exists in the newest build.

Thanks again,
Mingbo

**Comment by MingboPeng** [comment]
@chriswmackey  in new version, by default, if data is null, output data will be replaced by "-999".
![image](https://cloud.githubusercontent.com/assets/9031066/26061289/82de3b50-3955-11e7-91b9-660fbdf678bc.png)

**Comment by chriswmackey** [comment]
@MingboPeng ,

I am positive that the outputs that should be written in the file are not "null" as I ran the same model with the older Colibri components and I was able to get most of the results (all except a couple of iterations).

I think this is part of the issue, though.  The Agregator seems to sometimes write results into the file before the rest of the script has finished running.  So I'm pretty sure that the issue has to do with the Colibir thinking the script is finished running when it has not.

I'll try the new version when I get the chance and see if I can upload the file.
-Chris

**Comment by MingboPeng** [comment]
@chriswmackey , I guess I know why, in Aggregator, what "override" mode did you pick (right click the Aggregator)? by default, it will clean up the study folder first when you set Aggregator to "True", including the CSV file. I think you might selected the "Append to the end" mode, which won't delete the previous data.

If this is not the reason, please upload a case file for me to test.

Thanks again,
Mingbo

**Comment by MingboPeng** [comment]
@chriswmackey, I have recreated the problem, but still not clear what cause it, and digging it. Thanks for your comments.

Mingbo

**Comment by MingboPeng** [comment]
Hi @chriswmackey , this is what happens to your test. some outputs have "no data".
![image](https://cloud.githubusercontent.com/assets/9031066/26218186/186297aa-3bd8-11e7-83a3-57f46ed04b6a.png)

**Comment by bhowes-tt** [comment]
try if(DA.GetData)...

**Comment by chriswmackey** [comment]
@MingboPeng ,

I am glad that you were able to recreate it and you are right that, if the components were not executing in the right order, my script would have "no data" instead of a "null" values.  I really think it goes back to the execution order somehow.

Also, I know that I didn't touch the defaults of the aggregator.  So it's either appending to the end or cleaning up the files (whatever the default is).

Let me know if you still need me to upload something that recreates the issue but it sounds like what you have on your end is probably better than anything I could post.

-Chris

**Comment by MingboPeng** [comment]
@chriswmackey aggregator is always executed at the end. the problem happened to your csv is some outputs didn't compute correctly, and colibri didn't catch the \<null> \<empty> or \<no data was collected>, so the following data (in your case is img file string) moved to the front.

I have fixed this problem, please have a try when you have time.

Thanks again,
Mingbo
