### ISSUE TITLE
Default values for Steps (Iterator)

### ISSUE THREAD

**Issue by MingboPeng** [tt-acm/Colibri.Grasshopper#2]
Can we make steps have default values when nothing is connected?

**Comment by bhowes-tt** [comment]
Yeah for sure.  3 steps each - Min, Mean, Max?

**Comment by MingboPeng** [comment]
I will use whatever that Slider has.

**Comment by bhowes-tt** [comment]
What if the slider has a billion steps?  

I sort of like making users think about the granularity of the design space without having to mess with their sliders.  That's why I made that input mandatory in the first place.

**Comment by MingboPeng** [comment]
I totally agree with your idea that makes users think about their inputs. But I prefer to make users thinking at the first place in Sliders. To me, the steps is additional setting. 

Meanwhile, I don't know other practice, but for sustainability, we usually have exact values to test. Giving an unknown slider with a known steps, it is really hard to find out what exact values the Iterator will generate.

**Comment by bhowes-tt** [comment]
I think most GH users are less conscious of their sliders set up than you @MingboPeng , but I hear you.  

Maybe the easiest thing to do is what you recommended in the first place - use all sliders' steps if no steps input is provided.
