### ISSUE TITLE
Steps update does not change UI values

### ISSUE THREAD

**Issue by bhowes-tt** [tt-acm/Colibri.Grasshopper#3]
![image](https://cloud.githubusercontent.com/assets/3171551/21403168/a373fea6-c789-11e6-9809-a484808aa165.png)

From #1  - changing the Steps values does not update the number of iterations that the MessageBox reports to the user.  This happens after telling colibri to fly, then pressing no, then changing Steps values, then telling colibri to fly again.

**Comment by MingboPeng** [comment]
cool..Thanks
