### ISSUE TITLE
Aggregator inputs/outputs format with Units in "[ ]"

### ISSUE THREAD

**Issue by MingboPeng** [tt-acm/Colibri.Grasshopper#7]
need to take care of user's inputs with units

**Comment by bhowes-tt** [comment]
I'm not sure about this one...  

I think it makes good sense to leave this up to the author - users should name their inputs and outputs however they see fit, including units.  Sliders can describe quantities other than length, after all.

**Comment by MingboPeng** [comment]
Hi @bhowes-tt , I meant the original Aggregator will remove all "[" and "]" if user uses for their units. But this is fixed in [commit ](https://github.com/MingboPeng/Colibri.Grasshopper/commit/f4a8c6ef528d32f3d115964a70070c32a770f974)
