### ISSUE TITLE
Iterator steps

### ISSUE THREAD

**Issue by MingboPeng** [tt-acm/Colibri.Grasshopper#9]
Iterator skip over the step (2) when a slider was set to 1 to 4 integer, and no setting on Steps.

![image](https://cloud.githubusercontent.com/assets/9031066/21773834/870b3f70-d65e-11e6-8eec-b392ccca307e.png)

**Comment by bhowes-tt** [comment]
Nice catch @MingboPeng !  Fixed in the commit above.
